# Generated by Django 5.1.7 on 2025-03-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_allocation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(default='scheduled', max_length=20),
        ),
    ]
