# Generated by Django 5.1.7 on 2025-03-28 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_allocation', '0002_alter_room_room_type_alter_roomrequest_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='RoomOccupancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('room', models.ForeignKey(db_column='room_id_id', on_delete=django.db.models.deletion.CASCADE, to='room_allocation.room')),
            ],
            options={
                'verbose_name_plural': 'Room Occupancies',
            },
        ),
        migrations.DeleteModel(
            name='Room_occupency',
        ),
    ]
