# Generated by Django 5.1.7 on 2025-03-29 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_allocation', '0002_alter_room_room_type_alter_schedule_status'),
        ('room_allocation', '0003_alter_roomrequest_status_roomoccupancy_and_more'),
    ]

    operations = [
    ]
